server:
  port: ${SERVER_PORT:8090}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: bookstore
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST_NAME:localhost}:${RDS_PORT:3306}/bookstore?autoreconnect=true"
    username: ${RDS_USER_NAME:bookstore-user}
    password: ${RDS_PASSWORD:sawp~Fd385}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          timezone: UTC+2
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.springframework.security: TRACE


